### PR TITLE
Feat: configure backend ci

### PR DESCRIPTION
**Pull request by jarhead-killgrave**

### CODE REVIEW

**Comment by jarhead-killgrave** [comment]
@CodiumAI-Agent /review

**Comment by jarhead-killgrave** [comment]
@CodiumAI-Agent /describe

**Comment by jarhead-killgrave** [comment]
@CodiumAI-Agent /update_changelog

**Comment by jarhead-killgrave** [comment]
/update_changelog --pr_update_changelog.push_changelog_changes=true

**Comment by jarhead-killgrave** [comment]
@CodiumAI-Agent /update_changelog --pr_update_changelog.push_changelog_changes=true

**Review by JanaZebian — APPROVED** [review]

**Pull request merged**
