### PR TITLE
Feat/login logout

### PR DESCRIPTION
**Pull request by jarhead-killgrave**

### CODE REVIEW

**Comment by jarhead-killgrave** [comment]
Preparing review...

**Comment by jarhead-killgrave** [comment]
## PR Review 🔍

<table>
<tr>
<tr><td> ⏱️&nbsp;<strong>Estimated&nbsp;effort&nbsp;to&nbsp;review [1-5]</strong></td><td>

4, because the PR introduces a significant amount of changes across multiple files including security configurations, authentication mechanisms, and database schema updates. The complexity and potential impact of these changes on the system's security and functionality require a thorough review.


</td></tr>
<tr><td> 🧪&nbsp;<strong>Relevant tests</strong></td><td>

Yes


</td></tr>
<tr><td rowspan=2> ⚡&nbsp;<strong>Possible issues</strong></td>
<td>

<strong>Hardcoded Key Paths:</strong> The paths to the public and private keys are hardcoded in the application properties, which might not be flexible for different environments or secure storage options.</td></tr>
<tr>
<td>

<strong>Exception Handling:</strong> The current exception handling in the authentication flow might expose sensitive error details or not handle all potential error cases, leading to possible security vulnerabilities or poor error reporting.</td></tr>
<tr><td> 🔒&nbsp;<strong>Security concerns</strong></td><td>

No

</td></tr>
</table>


<details><summary> <strong>Code feedback:</strong></summary>

<hr><table><tr><td>relevant file</td><td>app/api/src/main/java/fr/imt/alumni/fil/config/AuthConfig.java
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Consider externalizing the key paths or using a more secure method to load these keys, such as from an environment variable or a secure vault solution. This change enhances the security by not exposing key paths in the codebase. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/jarhead-killgrave/agile-project-alumni-web-app/pull/31/files#diff-bb3a65ceb7e69c7252764f40d70aee65443e7cfceec8921615302af7f5a5ec65R33'>@Value("${classpath:public-key.pem}")</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>app/api/src/main/java/fr/imt/alumni/fil/config/AuthConfig.java
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Implement a more robust error handling mechanism for the JWT encoding and decoding processes to handle potential exceptions and errors gracefully. This improvement ensures that the system can recover from errors and provide more meaningful error messages to the client. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/jarhead-killgrave/agile-project-alumni-web-app/pull/31/files#diff-bb3a65ceb7e69c7252764f40d70aee65443e7cfceec8921615302af7f5a5ec65R54'>public JwtEncoder jwtEncoder() {</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>app/api/src/main/java/fr/imt/alumni/fil/config/SecurityConfig.java
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Add more granular access controls and permissions for different API endpoints based on user roles or other criteria. This enhancement will improve the security by ensuring that users can only access resources they are authorized to. [important]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/jarhead-killgrave/agile-project-alumni-web-app/pull/31/files#diff-ce93e069d9a57e6aaf0c8e670b87067a8c7971e08bbca92b7466e84865289dcdR67'>.anyRequest().authenticated()</a></td></tr></table><hr>

<table><tr><td>relevant file</td><td>app/api/src/main/java/fr/imt/alumni/fil/controller/AuthController.java
</td></tr><tr><td>suggestion &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>

<strong>

Refactor the authentication and registration endpoints to separate concerns more clearly and potentially use service classes to handle business logic. This change improves the modularity and maintainability of the code. [medium]

</strong>
</td></tr><tr><td>relevant line</td><td><a href='https://github.com/jarhead-killgrave/agile-project-alumni-web-app/pull/31/files#diff-921e2680e1e0bd8ca84af3187c74a203fa9dac7f43882419c54a00b335ec7d1fR48'>public ResponseEntity<AuthenticationResponse> register(@Valid @RequestBody RegisterRequestBody requestBody) {</a></td></tr></table><hr>

</details>

**Comment by jarhead-killgrave** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Comment by jarhead-killgrave** [comment]
## Generating PR code suggestions


Work in progress ...<br>

**Review by JanaZebian — APPROVED** [review]

**Pull request merged**
